# config/meta.yml

meta_product_name: "Parenter"
meta_title: "Parenter - Find Nannies"
meta_description: "Hire nannies in your neighborhood"
meta_image: "Parenter-logo-2_auto_x2.png" # should exist in `app/assets/images/`
